[tool.black]
line-length = 120
target-version = ['py310']

[tool.isort]
py_version = 310
profile = 'black'
src_paths = ['.']
length_sort = true
import_heading_firstparty = 'Project'
sections = 'FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'
